version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-50-16-225-96.compute-1.amazonaws.com
            database: d3eacmrd18bghj
            user: oceslqlzyaxiog
            password: f70e2dff83d3ae1b5e99ea71b95837f15e7e139e88dc63d69c00bc529a33cd65
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true